### ISSUE TITLE
How to view playground without the "/" path?

### ISSUE THREAD

**Issue by kaname-png** [harlan-zw/nuxt-og-image#15]
### Details

Currently when you want to access the playground without the path "/" using the composables of this package, it is not possible because an error appears in the console saying that the path "/" is required to use the composables of the package. Is there any way to see the playground without the "/" path needing to use it?

```
[nuxt] [request error] [unhandled] [500] 500 The path / is missing the og-image payload. (/api/og-image-options?path=/)                                                                                         21:43:46  
  at async Object.handler (/C:/Users/inmor/Documents/Proyectos/Naeko/dashboard/.nuxt/dev/index.mjs:1180:19)
  at async Object.handler (/C:/Users/inmor/Documents/Proyectos/Naeko/dashboard/node_modules/.pnpm/h3@1.4.0/node_modules/h3/dist/index.mjs:990:19)
  at async Server.toNodeHandle (/C:/Users/inmor/Documents/Proyectos/Naeko/dashboard/node_modules/.pnpm/h3@1.4.0/node_modules/h3/dist/index.mjs:1065:7)
```

**Comment by harlan-zw** [comment]
Hey @kaname-png, thanks for the issue.

Just checking if you were able to resolve this?
