### ISSUE TITLE
Integrate with @nuxtjs/i18n locale redirects

### ISSUE THREAD

**Issue by adinvadim** [harlan-zw/nuxt-og-image#27]
### Describe the bug

og-image doesnt work, /api/og-image-html return 500 and throw error `Cannot convert undefined or null to object`

```
[nuxt] [request error] [unhandled] [500] Cannot convert undefined or null to object                      20:52:01
  at Function.entries (<anonymous>)
  at normaliseEntryTags (./node_modules/unhead/dist/index.mjs:724:10)
  at Object.resolveTags (./node_modules/unhead/dist/index.mjs:935:33)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async renderSSRHead (./node_modules/@unhead/ssr/dist/index.mjs:77:23)
  at async ./.nuxt/dev/index.mjs:5124:21
  at async Object.handler (./node_modules/h3/dist/index.mjs:1247:19)
  at async toNodeHandle (./node_modules/h3/dist/index.mjs:1322:7)
  at async ufetch (./node_modules/unenv/runtime/fetch/index.mjs:9:17)
  at async $fetchRaw2 (./node_modules/ofetch/dist/shared/ofetch.502a4799.mjs:180:24)
[nuxt] [request error] [unhandled] [500] Cannot convert undefined or null to object                      20:52:01
  at Function.entries (<anonymous>)
  at normaliseEntryTags (./node_modules/unhead/dist/index.mjs:724:10)
  at Object.resolveTags (./node_modules/unhead/dist/index.mjs:935:33)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async renderSSRHead (./node_modules/@unhead/ssr/dist/index.mjs:77:23)
  at async ./.nuxt/dev/index.mjs:5124:21
  at async Object.handler (./node_modules/h3/dist/index.mjs:1247:19)
  at async toNodeHandle (./node_modules/h3/dist/index.mjs:1322:7)
  at async ufetch (./node_modules/unenv/runtime/fetch/index.mjs:9:17)
  at async $fetchRaw2 (./node_modules/ofetch/dist/shared/ofetch.502a4799.mjs:180:24)
[nuxt] [request error] [unhandled] [500]  (500  (/api/og-image-html?path=/ru/proxy/proxy-sale.com-ipv6&options=%7B%22path%22:%22/ru/proxy/proxy-sale.com-ipv6%22,%22component%22:%22OgImageBasic%22,%22width%22:1200,%22height%22:630,%22title%22:%22Proxy+Sale%22,%22provider%22:%22satori%22,%22static%22:true%7D))
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async Object.createVNode (./.nuxt/dev/index.mjs:4892:18)
  at async Object.createSvg (./.nuxt/dev/index.mjs:4912:20)
  at async Object.createPng (./.nuxt/dev/index.mjs:4886:17)
  at async Object.handler (./node_modules/h3/dist/index.mjs:1247:19)
  at async Server.toNodeHandle (./node_modules/h3/dist/index.mjs:1322:7)
```

### System / Nuxt Info

```Shell
System:
    OS: macOS 13.2
    CPU: (10) arm64 Apple M1 Max
    Memory: 1.03 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.12.1 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 111.0.5563.64
    Safari: 16.3

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.3.1`
- Nitro Version:    `2.3.1`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------
```

**Comment by adinvadim** [comment]
While debugging this error:

In dist/runtime/nitro/routes/html.mjs renderIsland string with plain HTML
```
  const island = await renderIsland(options);
  console.log('island', island);

// island <!DOCTYPE html><html><head><meta http-equiv="refresh" content="0; url=/ru"></head></html>  
```
And that's why
```
  head.push(island.head); // → head.push(undefined)

```

But why fetch /__nuxt_island/${payload.component} return plain string I dont solve yet

**Comment by adinvadim** [comment]
In nuxt.config I have this:

```
  experimental: {
    componentIslands: true,
  },
```

**Comment by adinvadim** [comment]
I think this problem is caused by nuxt i18n and option in nuxt.config i18n.strategy = 'prefix'

**Comment by harlan-zw** [comment]
Looks like a bug with Unhead not being able to handle a null entry `useHead(null)` from the nuxt i18n module. 

I've pushed up a fix to Unhead which will filter out these entries so it won't throw an exception.

Not too sure why this would throw an error on this page though and what the nuxt i18n module is doing, will keep open to investigate further.

**Comment by harlan-zw** [comment]
Hm I see, looks like I'll need to add support for @nuxtjs/i18n

**Comment by harlan-zw** [comment]
Hey, just had some time to get back to this issue. I'll need your nuxt.config or a StackBlitz to try and fix it, I'm not exactly sure how you're doing the redirect or how it connects to how this module works.

**Comment by harlan-zw** [comment]
Going to close for now as I'm trying to close all issues off for the v2 stable release coming. Will re-open if you can provide the details :)
