### ISSUE TITLE
WASM has not been initialized. Call `initialize` function. SEOKit

### ISSUE THREAD

**Issue by titogarrido** [harlan-zw/nuxt-og-image#59]
### Describe the bug

I am using "nuxt-seo-kit": "^1.3.8", When I try to access http://localhost:3001/__og_image__/og.png

I am receiving:
```
500

WASM has not been initialized. Call `initialize` function.

at svg2png (./node_modules/svg2png-wasm/dist/index.mjs:327:19)
at svg2png (./.nuxt/dev/index.mjs:1442:16)
at async Object.handler (./node_modules/h3/dist/index.mjs:1255:19)`
at async Server.toNodeHandle (./node_modules/h3/dist/index.mjs:1330:7)```


### Reproduction

I have installed SEOkit, now I am trying to test the og-image feature

### System / Nuxt Info

```Shell
System:
    OS: macOS 13.3.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 315.82 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
    npm: 9.7.1 - ~/.nvm/versions/node/v18.13.0/bin/npm
  Browsers:
    Chrome: 114.0.5735.133
    Firefox: 114.0.1
    Safari: 16.4

"devDependencies": {
    "@nuxt/devtools": "latest",
    "@nuxtjs/tailwindcss": "^6.7.0",
    "@pinia-plugin-persistedstate/nuxt": "^1.1.1",
    "@tailwindcss/forms": "^0.5.3",
    "@tailwindcss/typography": "^0.5.9",
    "@types/node": "^18",
    "@vueuse/core": "^10.1.2",
    "@vueuse/nuxt": "^10.1.2",
    "autoprefixer": "^10.4.14",
    "nuxt": "^3.5.2",
    "nuxt-headlessui": "^1.1.4",
    "nuxt-icon": "^0.4.1",
    "nuxt-seo-kit": "^1.3.8",
    "postcss": "^8.4.24",
    "tailwindcss": "^3.3.2"
  },
```

**Comment by titogarrido** [comment]
I am receiving an error if I click to preview the PNG.

Another thing that I just found, I am using docker to expose my website and somehow og-image is adding the PORT information from the container.

**Comment by harlan-zw** [comment]
Hi, please use the latest beta version explicitly. Nuxt SEO Kit will be upgraded soon.

**Comment by titogarrido** [comment]
Thanks!
