### ISSUE TITLE
Components PathPrefix:false in nuxt.config.ts breaks Lib

### ISSUE THREAD

**Issue by philippmunzert** [harlan-zw/nuxt-og-image#64]
### Describe the bug

Hi, at first very promising lib! Would love to get it working in my project.

I've set the path prefix option to `false` in my nuxt.config.ts. 

```js
// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
  modules: ['nuxt-og-image', 'nuxt-icon'],
  components: [
    {
      path: '~/components',
      pathPrefix: false, // <-- this
    },
  ],
});
```

This seems to break the support for the internal lib components llike `<OgImage />`. I also tried to play a little bit with the liv config:

```js
...
 ogImage: {
    componentDirs: ['~/components/OgImage']
  }
...
```

I see some errors in my console where nuxt is running:

```
[nuxt] [request error] [unhandled] [500]  (500 The path / is missing the og-image payload. (/api/og-image-options?path=/))          3:55:16 PM
  at async $fetchRaw2 (./node_modules/ofetch/dist/shared/ofetch.d438bb6f.mjs:234:14)  
  at async $fetch2 (./node_modules/ofetch/dist/shared/ofetch.d438bb6f.mjs:239:15)  
  at async fetchOptions (./.nuxt/dev/index.mjs:1559:15)  
  at async ./.nuxt/dev/index.mjs:2420:19  
  at async Object.handler (./node_modules/h3/dist/index.mjs:1284:19)  
  at async Server.toNodeHandle (./node_modules/h3/dist/index.mjs:1359:7)
 ```
 
 and also in the Browser Console like in the Reproduction:
 
 ```
 blitz.e809191e.js:42 [nuxt] [request error] [unhandled] [404]  (404 Island component not found: undefined (/__nuxt_island/MyTemplate_NBc25afyoU?
 ```

But this has no effects. Would love the get some help on this problem. 

### Reproduction

https://stackblitz.com/edit/nuxt-starter-ubcxwu?file=nuxt.config.ts

### System / Nuxt Info

```Shell
- Operating System: `Darwin`
- Node Version:     `v18.14.2`
- Nuxt Version:     `3.6.2`
- Nitro Version:    `2.5.2`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `ssr`, `modules`, `directus`, `image`, `gsap`, `app`, `runtimeConfig`, `build`, `components`, `sitemap`, `nitro`, `experimental`, `ogImage`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.8.0`, `@vueuse/nuxt@10.2.1`, `@hypernym/nuxt-gsap@2.2.2`, `nuxt-directus@5.4.4`, `@nuxt/image@1.0.0-rc.1`, `nuxt-simple-sitemap@2.7.0`, `nuxt-og-image@2.0.4`
- Build Modules:    `-`
```

**Comment by harlan-zw** [comment]
Hey, thanks for the issue.

I think this is a limitation with Nuxt Islands, they need the path prefix, will need to investigate more. For now, you can see if the following helps

```ts
 components: [
    {
      path: '~/components',
      pathPrefix: false, // <-- this
    },
   {
      path: '~/components/OgImage',
      pathPrefix: true
    },
  ],
```

**Comment by harlan-zw** [comment]
This is fixed in the latest version :)
